version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

  server:
    build:
      context: ./server/src
      dockerfile: RatingTracker.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=RankingDb;User Id=sa;Password=YourStrong!Password;TrustServerCertificate=True;
    networks:
      - app-network
    depends_on:
      - sqlserver

  client:
    build:
      context: ./client/rating-tracker
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:

volumes:
  sqlserver_data: