// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RatingTracker.Infrastructure.Data;

#nullable disable

namespace RatingTracker.Infrastructure.Migrations
{
    [DbContext(typeof(RankingDbContext))]
    partial class RankingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RatingTracker.Domain.Entitites.Ranking", b =>
                {
                    b.Property<Guid>("RaningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchEngine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetDomain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopRanking")
                        .HasColumnType("int");

                    b.HasKey("RaningId");

                    b.ToTable("Rankings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
